Update storm-0.9.0.1, fix deb scripts

diff --git a/storm.postrm b/storm.postrm
--- a/storm.postrm
+++ b/storm.postrm
@@ -1,11 +1,30 @@
 #!/bin/sh
 set -e
 
-/usr/sbin/deluser storm
+# summary of how this script can be called:
+#        * <postrm> `remove'
+#        * <postrm> `purge'
+#        * <old-postrm> `upgrade' <new-version>
+#        * <new-postrm> `failed-upgrade' <old-version>
+#        * <new-postrm> `abort-install'
+#        * <new-postrm> `abort-install' <old-version>
+#        * <new-postrm> `abort-upgrade' <old-version>
+#        * <disappearer's-postrm> `disappear' <overwriter>
+#          <overwriter-version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
 
-#DEBHELPER#
+case "$1" in
+    purge)
+        deluser --quiet --system storm >/dev/null || true
+    ;;
 
-[ "$1" = "configure" ] && ldconfig
+    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
+    ;;
 
-exit 0
+    *)
+        echo "postrm called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
 
